target-version = "py312"
extend-exclude = ["custom_components/four_noks/vendor", "test_config"]

[lint]
select = [
    "B",   # flake8-bugbear
    "C4",  # flake8-comprehensions
    "D",   # pydocstyle
    "E",   # pycodestyle
    "F",   # pyflakes
    "FLY", # flynt
    "G",   # flake8-logging-format
    "I",   # isort
    "LOG", # flake8-logging
    "PERF",# Perflint
    "PIE", # flake8-pie
    "PT",  # flake8-pytest-style
    "RET", # flake8-return
    "RSE", # flake8-raise
    "RUF", # Ruff-specific rules
    "SIM", # flake8-simplify
    "SLF", # flake8-self
    "T20", # flake8-print
    "UP",  # pyupgrade
    "W",   # pycodestyle
]

ignore = [
    "D202",
    "D203",
    "D213",
    "RUF012",
]

[lint.per-file-ignores]
"tests/*" = [
    "D",
    "PT022",
]
"scripts/*" = [
    "T201",
]


[lint.isort]
combine-as-imports = true
force-sort-within-sections = true
