name: HACS

on:
  push:
    branches-ignore:
      - main
  pull_request:
  schedule:
    - cron: "11 3 * * *"

jobs:
  hacs:
    name: HACS Action
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: HACS Action
        uses: "hacs/action@main"
        with:
          category: "integration"
