name: Lint

on:
  push:
    branches-ignore:
      - main
  pull_request:
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  ruff:
    name: Ruff
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install --requirement requirements_lint.txt

      - name: Run Ruff
        run: |
          python -m ruff check .
          python -m ruff format --check .
