name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 0 */7 * *"

jobs:
  pytest:
    name: Pytest
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/home-assistant/home-assistant:dev
    steps:
      - name: Check out repository
        uses: actions/checkout@v4

      - name: Install test dependencies
        run: |
          pip install --no-cache-dir pytest-asyncio

      - name: Run tests
        run: |
          pytest tests/ -v
